name: Build

on:
  push:
    branches:
      - "master"
    # paths-ignore:
    #   - "*.md"
    #   - "*.sh"
    #   - "release.yaml"
    #   - "sync_frp.yaml"

  workflow_dispatch:

jobs:
  go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GO_ARCH: [ "386", amd64, arm, arm64 ]
    steps:
      - uses: actions/checkout@v3

      - name: Download FRP Source Code
        run: |
          cd $GITHUB_WORKSPACE/android
          chmod +x *.sh
          
          ./install_src.sh

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.3
          cache-dependency-path: ${{ github.workspace }}/android/frp-*/go.sum

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/android
          chmod +x *.sh
          GOARCH=${{ matrix.GO_ARCH }}                   
                   
          declare -A goarch2cc=( ["arm64"]="aarch64-linux-android32-clang" ["arm"]="armv7a-linux-androideabi32-clang" ["amd64"]="x86_64-linux-android32-clang" ["386"]="i686-linux-android32-clang")
          export CC="$ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/${goarch2cc[$GOARCH]}"
          
          declare -A arch2lib=( ["arm64"]="arm64-v8a" ["arm"]="armeabi-v7a" ["amd64"]="x86_64" ["386"]="x86")
          export LIB="${arch2lib[$GOARCH]}"
          
          ./install_frp.sh frpc $GOARCH $LIB 
          ./install_frp.sh frps $GOARCH $LIB 

      - name: Upload to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "app_libs"
          path: "${{ github.workspace }}/app/libs"
